# Generated by Django 6.0.5 on 2026-05-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-name',), 'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'description')},
        ),
    ]
